"""Rebuild docs helpers exposed from the aideator package."""

from __future__ import annotations

from pathlib import Path

from db.reports import get_report
from db.runs import list_runs


def _render_report_markdown(*, idea_id: str, cards: list[dict[str, object]]) -> str:
    lines: list[str] = [f"# Idea Report {idea_id}", ""]

    order = ["demand", "competition", "risk", "next_steps"]
    for card_type in order:
        card = next((item for item in cards if str(item.get("type")) == card_type), None)
        if card is None:
            continue
        lines.append(f"## {card_type.replace('_', ' ').title()}")
        lines.append(str(card.get("summary", "")))
        citations = card.get("citation_urls", [])
        if isinstance(citations, list) and citations:
            lines.append("")
            lines.append("Citations:")
            for url in citations:
                lines.append(f"- {url}")
        lines.append("")

    lines.append("## Cursor/Claude Code Usage Notes")
    lines.append("Generated by rebuild-docs command.")
    lines.append("")
    return "\n".join(lines)


def rebuild_docs(*, output_dir: str = "docs") -> dict[str, object]:
    target = Path(output_dir)
    target.mkdir(parents=True, exist_ok=True)

    written = 0
    for run in list_runs():
        if run.status != "succeeded":
            continue
        report = get_report(run.run_id)
        if report is None:
            continue
        file_path = target / f"idea-{run.idea_id}.md"
        file_path.write_text(
            _render_report_markdown(idea_id=str(run.idea_id), cards=report.cards),
            encoding="utf-8",
        )
        written += 1

    return {"written": written, "output_dir": str(target)}


def run() -> dict[str, object]:
    return rebuild_docs()
